=== astercast/aster-da-master/api/v1/schema/network.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "network",
  "type": "object",
  "properties": {
    "version": {
      "type": "string"
    },
    "generated": {
      "type": "string"
    },
    "artist": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "name"
      ]
    },
    "nodes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "kind": {
            "enum": [
              "artist",
              "collaborator",
              "producer"
            ]
          },
          "track_count": {
            "type": "integer",
            "minimum": 0
          },
          "first_date": {
            "type": [
              "string",
              "null"
            ]
          },
          "last_date": {
            "type": [
              "string",
              "null"
            ]
          },
          "page": {
            "type": "string"
          },
          "tracks": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "title": {
                  "type": "string"
                },
                "date": {
                  "type": [
                    "string",
                    "null"
                  ]
                },
                "plays": {
                  "type": [
                    "integer",
                    "null"
                  ]
                }
              },
              "required": [
                "title"
              ]
            }
          },
          "years": {
            "type": "array",
            "items": {
              "type": "integer"
            }
          },
          "x": {
            "type": "number"
          },
          "y": {
            "type": "number"
          },
          "r": {
            "type": "number"
          }
        },
        "required": [
          "id",
          "name",
          "kind",
          "track_count",
          "page",
          "tracks",
          "years",
          "x",
          "y",
          "r"
        ]
      }
    },
    "edges": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "a": {
            "type": "string"
          },
          "b": {
            "type": "string"
          },
          "weight": {
            "type": "integer",
            "minimum": 1
          },
          "kind": {
            "enum": [
              "artist",
              "co-credit"
            ]
          },
          "shared_tracks": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "a",
          "b",
          "weight",
          "kind"
        ]
      }
    },
    "insights": {
      "type": "object",
      "properties": {
        "most_frequent_collaborator": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "track_count": {
              "type": "integer"
            }
          },
          "required": [
            "name",
            "track_count"
          ]
        },
        "producer_most_credits": {
          "type": [
            "object",
            "null"
          ],
          "properties": {
            "name": {
              "type": "string"
            },
            "track_count": {
              "type": "integer"
            }
          },
          "required": [
            "name",
            "track_count"
          ]
        },
        "year_most_collabs": {
          "type": "object",
          "properties": {
            "year": {
              "type": "integer"
            },
            "collab_tracks": {
              "type": "integer"
            }
          },
          "required": [
            "year",
            "collab_tracks"
          ]
        },
        "first_ever_collaborator": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "date": {
              "type": "string"
            },
            "title": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "date",
            "title"
          ]
        }
      },
      "required": [
        "most_frequent_collaborator",
        "producer_most_credits",
        "year_most_collabs",
        "first_ever_collaborator"
      ]
    }
  },
  "required": [
    "version",
    "generated",
    "artist",
    "nodes",
    "edges",
    "insights"
  ]
}

=== astercast/aster-da-master/data/v1/network.json
{
 "version": "0.19.0",
 "generated": "2026-10-11",
 "artist": {
  "id": "aster",
  "name": "Aster da Master"
 },
 "nodes": [
  {
   "id": "aster",
   "name": "Aster da Master",
   "kind": "artist",
   "track_count": 41,
   "first_date": null,
   "last_date": null,
   "page": "index.html",
   "tracks": [],
   "years": [
    2018,
    2019,
    2020,
    2021,
    2023,
    2024
   ],
   "x": 460,
   "y": 320,
   "r": 40
  },
  {
   "id": "max-ferrari",
   "name": "Max Ferrari",
   "kind": "collaborator",
   "track_count": 8,
   "first_date": "2018-08-20",
   "last_date": "2024-11-07",
   "page": "circle/index.html#c-max-ferrari",
   "tracks": [
    {
     "title": "DESTINY (ft. JAX & Max Ferrari) ~ [prod. louky]",
     "date": "2018-08-20",
     "plays": 2000
    },
    {
     "title": "NIGHT MODE ft. MAX FERRARI x YUNG VETTA x JAX",
     "date": "2019-06-13",
     "plays": 10083
    },
    {
     "title": "This Feeling's Newer ft. Max Ferrari (prod. odece)",
     "date": "2021-07-14",
     "plays": 211
    },
    {
     "title": "Got Knots ft. Max Ferrari (prod. lil biscuit)",
     "date": "2021-07-14",
     "plays": 174
    },
    {
     "title": "Mix Up Substances ft. Max Ferrari",
     "date": "2021-07-14",
     "plays": 151
    },
    {
     "title": "MRari inna Beanstalk w/ Max Ferrari (@mvvi468)",
     "date": "2024-04-05",
     "plays": 515
    },
    {
     "title": "Sti11 waiting/tunnel freestyle w/ Max Ferrari prod. suli",
     "date": "2024-11-07",
     "plays": 300
    },
    {
     "title": "ARCSNOWWW w/ Max Ferrari prod. sustain",
     "date": "2024-11-07",
     "plays": 184
    }
   ],
   "years": [
    2018,
    2019,
    2021,
    2024
   ],
   "x": 460.0,
   "y": 170.0,
   "r": 34.0
  },
  {
   "id": "yung-vetta",
   "name": "Yung Vetta",
   "kind": "collaborator",
   "track_count": 7,
   "first_date": "2018-12-02",
   "last_date": "2019-06-13",
   "page": "circle/index.html#c-yung-vetta",
   "tracks": [
    {
     "title": "Hip On My Blade (ft. Yung Vetta) ~ [prod. Skel]",
     "date": "2018-12-02",
     "plays": 1368
    },
    {
     "title": "Ima Be There ft. Yung Vetta(prod. Why Loner)",
     "date": "2019-01-21",
     "plays": 1913
    },
    {
     "title": "[outro] Off Beat ft. Yung Vetta (prod. Addy)",
     "date": "2019-01-28",
     "plays": 935
    },
    {
     "title": "STOP IT! ft. Yung Vetta (prod. okthxbb)",
     "date": "2019-01-28",
     "plays": 455
    },
    {
     "title": "Hard To Keep ft. Yung Vetta (prod. Dead Spyro X Scarlet)",
     "date": "2019-01-28",
     "plays": 2415
    },
    {
     "title": "Nothing ft. Yung Vetta(prod Xtravulous)",
     "date": "2019-01-28",
     "plays": 724
    },
    {
     "title": "NIGHT MODE ft. MAX FERRARI x YUNG VETTA x JAX",
     "date": "2019-06-13",
     "plays": 10083
    }
   ],
   "years": [
    2018,
    2019
   ],
   "x": 566.1,
   "y": 213.9,
   "r": 31.2
  },
  {
   "id": "jax",
   "name": "JAX",
   "kind": "collaborator",
   "track_count": 3,
   "first_date": "2018-08-20",
   "last_date": "2019-06-13",
   "page": "circle/index.html#c-jax",
   "tracks": [
    {
     "title": "DESTINY (ft. JAX & Max Ferrari) ~ [prod. louky]",
     "date": "2018-08-20",
     "plays": 2000
    },
    {
     "title": "Walk With Me w/ JAX (Prod. Rawman)",
     "date": "2018-08-27",
     "plays": 700
    },
    {
     "title": "NIGHT MODE ft. MAX FERRARI x YUNG VETTA x JAX",
     "date": "2019-06-13",
     "plays": 10083
    }
   ],
   "years": [
    2018,
    2019
   ],
   "x": 610.0,
   "y": 320.0,
   "r": 20.2
  },
  {
   "id": "lil-yu",
   "name": "lil yu",
   "kind": "collaborator",
   "track_count": 3,
   "first_date": "2019-12-22",
   "last_date": "2023-08-29",
   "page": "circle/index.html#c-lil-yu",
   "tracks": [
    {
     "title": "I'd rather be w/ lil yu (prod. razorwrist)",
     "date": "2019-12-22",
     "plays": 1343
    },
    {
     "title": "playin' by the book w/ lil yu (prod. dxsh)",
     "date": "2020-10-07",
     "plays": 861
    },
    {
     "title": "Clock In The Benz w/ Lil Yu prod shinju",
     "date": "2023-08-29",
     "plays": 725
    }
   ],
   "years": [
    2019,
    2020,
    2023
   ],
   "x": 566.1,
   "y": 426.1,
   "r": 20.2
  },
  {
   "id": "griimxo",
   "name": "Griimxo",
   "kind": "collaborator",
   "track_count": 2,
   "first_date": "2024-08-24",
   "last_date": "2024-11-08",
   "page": "circle/index.html#c-griimxo",
   "tracks": [
    {
     "title": "Phantom Moshpit (feat. GRiiMXO)",
     "date": "2024-08-24",
     "plays": null
    },
    {
     "title": "Phantom Moshpit w/ Griimxo (remastered) prod. scared716",
     "date": "2024-11-08",
     "plays": 178
    }
   ],
   "years": [
    2024
   ],
   "x": 460.0,
   "y": 470.0,
   "r": 17.5
  },
  {
   "id": "jo-e-dripp",
   "name": "JO$E DRIPP",
   "kind": "collaborator",
   "track_count": 2,
   "first_date": "2018-04-28",
   "last_date": "2019-07-06",
   "page": "circle/index.html#c-jo-e-dripp",
   "tracks": [
    {
     "title": "Mistakes Ft. JO$E DRIPP (prod. Tec)",
     "date": "2018-04-28",
     "plays": 1400
    },
    {
     "title": "SUN SET FOR U ft. JO$E DRIPP (prod. y axis)",
     "date": "2019-07-06",
     "plays": 1771
    }
   ],
   "years": [
    2018,
    2019
   ],
   "x": 353.9,
   "y": 426.1,
   "r": 17.5
  },
  {
   "id": "lilvicbxi",
   "name": "LILVICBXI",
   "kind": "collaborator",
   "track_count": 2,
   "first_date": "2019-12-22",
   "last_date": "2019-12-22",
   "page": "circle/index.html#c-lilvicbxi",
   "tracks": [
    {
     "title": "snow caps w/ LILVICBXI (prod. LILVICBXI x spliff08_)",
     "date": "2019-12-22",
     "plays": 1579
    },
    {
     "title": "same amount w/ LILVICBXI (prod. LILVICBXI)",
     "date": "2019-12-22",
     "plays": 2991
    }
   ],
   "years": [
    2019
   ],
   "x": 310.0,
   "y": 320.0,
   "r": 17.5
  },
  {
   "id": "lil-wintr",
   "name": "Lil Wintr",
   "kind": "collaborator",
   "track_count": 2,
   "first_date": "2019-12-06",
   "last_date": "2019-12-06",
   "page": "circle/index.html#c-lil-wintr",
   "tracks": [
    {
     "title": "Master Key (feat. Lil Wintr & Marcelo)",
     "date": "2019-12-06",
     "plays": null
    },
    {
     "title": "master key ft. Lil Wintr x Marcelo (prod. ginseng)",
     "date": "2019-12-06",
     "plays": 9615
    }
   ],
   "years": [
    2019
   ],
   "x": 353.9,
   "y": 213.9,
   "r": 17.5
  },
  {
   "id": "marcelo",
   "name": "Marcelo",
   "kind": "collaborator",
   "track_count": 2,
   "first_date": "2019-12-06",
   "last_date": "2019-12-06",
   "page": "circle/index.html#c-marcelo",
   "tracks": [
    {
     "title": "Master Key (feat. Lil Wintr & Marcelo)",
     "date": "2019-12-06",
     "plays": null
    },
    {
     "title": "master key ft. Lil Wintr x Marcelo (prod. ginseng)",
     "date": "2019-12-06",
     "plays": 9615
    }
   ],
   "years": [
    2019
   ],
   "x": 460.0,
   "y": 99.2,
   "r": 17.5
  },
  {
   "id": "capoxxo",
   "name": "capoxxo",
   "kind": "collaborator",
   "track_count": 2,
   "first_date": "2019-10-04",
   "last_date": "2019-12-22",
   "page": "circle/index.html#c-capoxxo",
   "tracks": [
    {
     "title": "candy w/ capoxxo(prod. razorwrist)",
     "date": "2019-10-04",
     "plays": 11587
    },
    {
     "title": "getting colder w/ capoxxo (prod. pvscale x asa41)",
     "date": "2019-12-22",
     "plays": 4587
    }
   ],
   "years": [
    2019
   ],
   "x": 564.1,
   "y": 121.1,
   "r": 17.5
  },
  {
   "id": "ammi-age",
   "name": "AMMI $AGE",
   "kind": "collaborator",
   "track_count": 1,
   "first_date": "2019-07-06",
   "last_date": "2019-07-06",
   "page": "circle/index.html#c-ammi-age",
   "tracks": [
    {
     "title": "I'M WEAKENING ft. AMMI $AGE",
     "date": "2019-07-06",
     "plays": 2490
    }
   ],
   "years": [
    2019
   ],
   "x": 647.6,
   "y": 182.3,
   "r": 14.8
  },
  {
   "id": "keyblayde808",
   "name": "Keyblayde808",
   "kind": "collaborator",
   "track_count": 1,
   "first_date": "2019-12-30",
   "last_date": "2019-12-30",
   "page": "circle/index.html#c-keyblayde808",
   "tracks": [
    {
     "title": "White Noise ft. Keyblayde808 (prod. Keyblayde808)",
     "date": "2019-12-30",
     "plays": 2650
    }
   ],
   "years": [
    2019
   ],
   "x": 694.0,
   "y": 270.9,
   "r": 14.8
  },
  {
   "id": "lilrareboy",
   "name": "Lilrareboy",
   "kind": "collaborator",
   "track_count": 1,
   "first_date": "2021-07-14",
   "last_date": "2021-07-14",
   "page": "circle/index.html#c-lilrareboy",
   "tracks": [
    {
     "title": "Sunvalley Rally ft. Lilrareboy (prod. phantasie)",
     "date": "2021-07-14",
     "plays": 319
    }
   ],
   "years": [
    2021
   ],
   "x": 694.0,
   "y": 369.1,
   "r": 14.8
  },
  {
   "id": "max",
   "name": "Max",
   "kind": "collaborator",
   "track_count": 1,
   "first_date": "2024-11-05",
   "last_date": "2024-11-05",
   "page": "circle/index.html#c-max",
   "tracks": [
    {
     "title": "nitemode2019 w/ Max+Vetty prod. NaXi.wav",
     "date": "2024-11-05",
     "plays": 17
    }
   ],
   "years": [
    2024
   ],
   "x": 647.6,
   "y": 457.7,
   "r": 14.8
  },
  {
   "id": "offline-hp",
   "name": "Offline_hp",
   "kind": "collaborator",
   "track_count": 1,
   "first_date": "2019-06-26",
   "last_date": "2019-06-26",
   "page": "circle/index.html#c-offline-hp",
   "tracks": [
    {
     "title": "GARDEN ft. Offline_hp (prod. QB)",
     "date": "2019-06-26",
     "plays": 1311
    }
   ],
   "years": [
    2019
   ],
   "x": 564.1,
   "y": 518.9,
   "r": 14.8
  },
  {
   "id": "spursy",
   "name": "SPURSY",
   "kind": "collaborator",
   "track_count": 1,
   "first_date": "2020-05-08",
   "last_date": "2020-05-08",
   "page": "circle/index.html#c-spursy",
   "tracks": [
    {
     "title": "Yea Thats Kool (feat. ASTERDAMASTER & SPURSY)",
     "date": "2020-05-08",
     "plays": null
    }
   ],
   "years": [
    2020
   ],
   "x": 460.0,
   "y": 540.8,
   "r": 14.8
  },
  {
   "id": "shola",
   "name": "Shola",
